### ISSUE TITLE
Re-binding pins after creating new instance of Observablecollection<Pin>

### ISSUE THREAD

**Issue by mkopljar** [nuitsjp/Xamarin.Forms.GoogleMaps.Bindings#13]
Hi !
Is there a way to re-bind Pins to new instance of Observablecollection<Pin> ? 
Doing 
   Pins = new Observablecollection<Pin>(new_pins);

creates a new instance of Pins, so binding no longer updates UI. 
Is there a work around ?

**Comment by nuitsjp** [comment]
* Provide a function to bind Pins of Map to ViewModel.
* Do not provide a function to bind Observablecollection of ViewModel to Pins.

This is impossible from the outside because of Map constraint.

Clear the Pins bound to the ViewModel and add it again.

**Comment by mkopljar** [comment]
Sorry I don't understand ? 
What do you mean by 
"Provide a function to bind Pins of Map to ViewModel.
Do not provide a function to bind Observablecollection of ViewModel to Pins." ?

**Comment by nuitsjp** [comment]
I am sorry that my English is not good.

BindingPinsBehavior works in reverse to ordinary binding.
In MVVM pattern, in normal Binding, set the property of ViewModel to the property of View.

But BindingPinsBehavior binds View properties (ie Map's Pins) to ViewModel.
So you can not new ObservableCollection and bind it to a Map.

Because pins is Readonly.
https://github.com/amay077/Xamarin.Forms.GoogleMaps/blob/master/Xamarin.Forms.GoogleMaps/Xamarin.Forms.GoogleMaps/Map.cs#L195

**Comment by nuitsjp** [comment]
I saw this Issue.
https://github.com/amay077/Xamarin.Forms.GoogleMaps/issues/529

In Xamarin.Forms.GoogleMaps.Bindings, there is nothing you can do from the outside.

**Comment by stefancvetkovic** [comment]
What is a best way to add pins in Binding way?
If I put only Pins.Add(new Pin{...}) then I got null reference exception, because I need to initialize Observable<Pin> Pins object?
Can you provide some code example? How it would like for loading pins OnLoad or on a MapReady? thanks
